FROM crystallang/crystal:latest@sha256:34e3366af9d36561f040b48b85633ed68a39f1e941f3117376f5d9fd273c8e1c

LABEL io.whalebrew.name 'crystal'
LABEL io.whalebrew.config.working_dir '/workdir'
WORKDIR /workdir

ENTRYPOINT ["crystal"]
CMD ["--help"]