FROM artemklevtsov/r-alpine:latest@sha256:56807c80a0f8e14eca06988ca5bdc225937ef35ae8f8d1b53bde8c3bb3b7e0ca

LABEL io.whalebrew.name 'Rscript'
LABEL io.whalebrew.config.working_dir '/workdir'
WORKDIR /workdir

ENTRYPOINT ["Rscript"]
CMD ["--help"]
